// FrontendProjects/vite-project-BMIReact/src/App.tsx
import { Input } from './components/input'
import './App.css'
import { useState } from 'react'
import { BMIHeader } from './components/bmi_header'
import { BMIFooter } from './components/bmi_footer'
import { CalculatorButton } from './components/calculator_button'

function App() { 
  
  const [name, setName] = useState('')
  const [weight, setWeight] = useState('')
  const [height, setHeight] = useState('')

  const onChangeFunctionName = (event: any) => {
    setName(event.target.value);
  }

  const onChangeFunctionWeight = (event: any) => {
    setWeight(event.target.value);
  }

  const onChangeFunctionHeight = (event: any) => {
    setHeight(event.target.value);
  }

  const onClickHandler = () => {

    const BMI = Math.floor(Number(weight) / (Number(height) * Number(height)))
    
    alert(`${name} seu BMI é de ${BMI}`)
  }

  return (
    <div className="App">
      <div id='container'>
        <BMIHeader/>
        <main>
          <h2>Type your data</h2>
          <form action="#">
            <Input type = {'text'} label = {'Name: '} input={name} onChangeCallback={onChangeFunctionName} />
            <Input type = {'number'} label = {'Weight: '} input = {weight} onChangeCallback={onChangeFunctionWeight} />
            <Input type = {'number'} label = {'Height: '} input={height} onChangeCallback={onChangeFunctionHeight} />
            <CalculatorButton onClickCallback={onClickHandler} />  
          </form>
        </main>
        <BMIFooter/>
      </div>
    </div>
  )
}

export default App

// FrontendProjects/vite-project-BMISvelte/src/App.svelte
<script lang="ts">
  import Input from "./lib/input.svelte";
  import Form from "./lib/form.svelte";
  import CalculateButton from "./lib/calculate_button.svelte";

  let name : string
  let weight : string
  let height : string
</script>

<main>
  <div id='container'>
    <header>
      <h1>BMI Calculator</h1>
    </header>
    <main>
      <h2>Type your data</h2>
      <Form>
        <Input label={"Name: "} input={name} />
        <Input label={"Weight: "} input={weight} />
        <Input label={"Height: "} input={height} />
        <CalculateButton/>
      </Form>
    </main>
    <footer>
      <p>R1 Software @ 2023</p>
    </footer>
  </div>
</main>

<style>

</style>
